# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0dc096a749d8eff1f5d40a01b1f04f770d23a909595fc660d3f615f8572dce5246c878dfda93f8c63c9d4cc7ca242a572f8de4058bf1438d485691a35d43289

test:
  secret_key_base: 33f2ce3b3abfbe7c9c8c724d9ba4e4661f5fbaddd890ac882b7ca988c4eb265aefe9d8a3369a3bde6d3546c86263f92d98d3cf59d47493bdd6bfc0758bd67484

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
